services:
  postgres:
    image: postgres:15-alpine
    container_name: meteorisk_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: meteorisk_airflow
    restart: always
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - METEORISK_DB_URL=postgresql+psycopg2://meteorisk_user:meteorisk@postgres:5432/meteorisk_db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./extraction:/opt/airflow/extraction
      - ./transformation:/opt/airflow/transformation
      - ./load:/opt/airflow/load
      - airflow_data:/opt/airflow
    ports:
      - "8080:8080"
    command: standalone
    depends_on:
      - postgres
 
